# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test Pyrkbun Python Library -> Unit
      env:
        PYRK_TEST_UNIT: 'True'
      run: |
          python3 -m unittest discover ./tests "test_unit.py" -v
    - name: Test Pyrkbun Python Library -> Integration
      env:
        PYRK_API_KEY: ${{ secrets.PYRK_API_KEY }}
        PYRK_API_SECRET_KEY: ${{ secrets.PYRK_API_SECRET_KEY }}
        PYRK_TEST_DOMAIN_NAME: ${{ secrets.PYRK_TEST_DOMAIN_NAME }}
        PYRK_TEST_PRICING: 'True'
        PYRK_TEST_PING: 'True'
        PYRK_TEST_DNS_RETRIEVE: 'True'
        PYRK_TEST_SSL: 'True'
        PYRK_TEST_DNS_CREATE: 'True'
        PYRK_TEST_DNS_DELETE: 'True'
        PYRK_TEST_DNS_MODIFY: 'True'
        PYRK_RATE: '5'
        PYRK_RETRIES: '3'
        PYTHONPATH: ${{ github.workspace }}
      run: |
          python3 -m unittest discover ./tests "test_integration.py" -v
    - name: Test Pyrkbun CLI -> Integration
      env:
        PYRK_API_KEY: ${{ secrets.PYRK_API_KEY }}
        PYRK_API_SECRET_KEY: ${{ secrets.PYRK_API_SECRET_KEY }}
        PYRK_TEST_DOMAIN_NAME: ${{ secrets.PYRK_TEST_DOMAIN_NAME }}
        PYRK_TEST_CLI_PING: 'True'
        PYRK_TEST_CLI_PRICING: 'True'
        PYRK_TEST_CLI_SSL: 'True'
        PYRK_TEST_CLI_DNS_RETRIEVE: 'True'
        PYRK_TEST_CLI_DNS_CREATE: 'True'
        PYRK_TEST_CLI_DNS_DELETE: 'True'
        PYRK_TEST_CLI_DNS_MODIFY: 'True'
        PYRK_RATE: '5'
        PYRK_RETRIES: '3'
        PYTHONPATH: ${{ github.workspace }}
      run: |
          python3 -m unittest discover ./tests "test_cli.py" -v
    - name: Test Pyrkbun Bulk CLI -> Integration
      env:
        PYRK_API_KEY: ${{ secrets.PYRK_API_KEY }}
        PYRK_API_SECRET_KEY: ${{ secrets.PYRK_API_SECRET_KEY }}
        PYRK_TEST_DOMAIN_NAME: ${{ secrets.PYRK_TEST_DOMAIN_NAME }}
        PYRK_TEST_CLI_DNS_BULK: 'True'
        PYRK_RATE: '5'
        PYRK_RETRIES: '3'
        PYTHONPATH: ${{ github.workspace }}
      run: |
          python3 -m unittest discover ./tests "test_cli.py" -v